// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR_ilDZbo9hPR0JJ2Wtal555N8VVWvqEQ',
    appId: '1:549455573441:web:a198bb1adb5f3b35c4ff40',
    messagingSenderId: '549455573441',
    projectId: 'aksab-erp',
    authDomain: 'aksab-erp.firebaseapp.com',
    databaseURL: 'https://aksab-erp-default-rtdb.firebaseio.com',
    storageBucket: 'aksab-erp.firebasestorage.app',
    measurementId: 'G-7GGD70EHNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Nu0SHkkoSQi9gMjxNK5pfnqbKSrS5fg',
    appId: '1:549455573441:android:e74e7453b56482c1c4ff40',
    messagingSenderId: '549455573441',
    projectId: 'aksab-erp',
    databaseURL: 'https://aksab-erp-default-rtdb.firebaseio.com',
    storageBucket: 'aksab-erp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ry1_Fd-CLmDrVfDyJMaUHq5nEnEOIGw',
    appId: '1:549455573441:ios:047fea0fe19f1415c4ff40',
    messagingSenderId: '549455573441',
    projectId: 'aksab-erp',
    databaseURL: 'https://aksab-erp-default-rtdb.firebaseio.com',
    storageBucket: 'aksab-erp.firebasestorage.app',
    iosBundleId: 'com.example.myTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7ry1_Fd-CLmDrVfDyJMaUHq5nEnEOIGw',
    appId: '1:549455573441:ios:047fea0fe19f1415c4ff40',
    messagingSenderId: '549455573441',
    projectId: 'aksab-erp',
    databaseURL: 'https://aksab-erp-default-rtdb.firebaseio.com',
    storageBucket: 'aksab-erp.firebasestorage.app',
    iosBundleId: 'com.example.myTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR_ilDZbo9hPR0JJ2Wtal555N8VVWvqEQ',
    appId: '1:549455573441:web:c216fb4de805ad46c4ff40',
    messagingSenderId: '549455573441',
    projectId: 'aksab-erp',
    authDomain: 'aksab-erp.firebaseapp.com',
    databaseURL: 'https://aksab-erp-default-rtdb.firebaseio.com',
    storageBucket: 'aksab-erp.firebasestorage.app',
    measurementId: 'G-R3XMLJ1SCR',
  );
}
